services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: maybee
      POSTGRES_PASSWORD: maybee
      POSTGRES_DB: maybee
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  backend:
    image: maybee-backend
    container_name: maybee-backend
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DB_URI: "postgresql://maybee:maybee@db:5432"
      LOGGING_LEVEL: "INFO"
      SECRET_KEY: "secret_key"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      REDIS_HOST: redis://redis-cache:6379
    networks:
      - mynetwork
  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - mynetwork 

volumes:
  cache:
    driver: local


networks:
  mynetwork:
    driver: bridge