name: Tag release with pyproject.toml version

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Get version
        id: version
        run: |
          # Extract the current version from pyproject.toml
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV


      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"

      - name: Push Git tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin "v${{ env.VERSION }}"
